spring.application.name=bot
spring.config.import=optional:file:.env[.properties]

# PostgreSQL (Intenta usar variables de entorno, o cae en valores por defecto si falla)
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-patient-truth-acfm8enz-pooler.sa-east-1.aws.neon.tech/bot-autmatizacion?sslmode=require&channelBinding=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_9yadXOofDVM7}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# GROQ
spring.ai.openai.api-key=${GROQ_API_KEY}

spring.ai.openai.base-url=https://api.groq.com/openai

spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

jwt.secret=mysupersecretkeymysupersecretkey123456
jwt.expiration=3600000